[pytest]
addopts = -s
          --headed
          --slowmo 1000
;          --tracing on
;          --video on
          #生成测试数据在report目录下allure generate report -o allure-report --clean,

          --alluredir=report
testpaths = script
python_files = test_*.py
python_classes = Test*
python_functions = test_*
