[pytest]
addopts = -s
          --headed
          --slowmo 2000
;          --tracing on
;          --video on
;          --alluredir=report

testpaths = script
python_files = 1test_*.py
python_classes = Test*
python_functions = test_*
